--- 
# These tasks install http and the php modules. 

 - set_fact:
     http_port: 80
     max_clients: 200                            

 # this was using yum: before but travis install didnt have yum
 # had to fix php to php5 and php-mysql to php5-mysql
 # and libsemanage-python and libselinux-python to python-all-dev
 # and httpd to apache2
 - name: Install http and php etc 
   apt: name={{ item }} state=present 
   with_items: 
    - apache2 
    - php5 
    - php5-mysql 
    - git 
    - python-all-dev 

#taking this out for now.  this was when we installed via httpd. 
#not sure what it needs to be yet for when doing apache2
# - name: write the apache config file                                                                                      
 #  template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf                                           
  # notify:                                                                                                                 
   # - restart apache                                                                                                        

#installing apache now so taking this out
# - name: http service state 
 #  service: name=httpd state=started enabled=yes 
