# handlers for spadeApache

 - name: restart apache  when using yum                                                                                 
   service: name=httpd state=restarted               

 - name: restart apache using apt-get
   service: name=apache2 state=restarted 
